name: cast_gnn
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - tqdm
  - meshio             # For .msh to .pt conversion
  - gmsh               # For mesh/meshgen.py
  - cadquery           # For step/3dgen.py
  - pyvista            # For visualization
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # For RTX 3060 acceleration
  - pyg                # PyTorch Geometric
  - pip:
    - pyvista[all]
    - trimesh